config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <div class="navbar-nav navbar-text d-flex justify-content-between flex-row mt-3">
        <%= link_to "List of restaurants", restaurants_path, class: "btn btn-primary" %>
        <%= link_to "Add a restaurant", new_restaurant_path, class: "btn btn-primary" %>
      </div>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h2 class="text-center">Restaurants</h2>

<div class="my-5">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to restaurant.name, restaurant_path(restaurant) %>
      <% count = 0 %>
      <% restaurant.reviews.each do |review| %>
        <% count += review.rating %>
      <% end %>
      <% if restaurant.reviews.length != 0 %>
        <span class="badge badge-primary badge-pill">
        <%= count / restaurant.reviews.length %> ⚝</span>
      <% end %>
    </li>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h2>Add a new restaurant</h2>

<%= simple_form_for(@restaurant) do |f| %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/restaurants/show.html.erb
<h2 class="font-italic text-center"><%= @restaurant.name %></h2>

<h4>Address</h4>
<p><%= @restaurant.address %></p>

<h4>Phone number</h4>
<p><%= @restaurant.phone_number %></p>

<h4>Category</h4>
<p><%= @restaurant.category %></p>

<hr>

<h3>Reviews</h3>

<div class="my-3">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item d-flex justify-content-between align-items-center"><%= review.content %><span class="badge badge-primary badge-pill"><%= review.rating %></span></li>
  <% end %>
</div>

<hr>

<div class="my-3">
  <%= simple_form_for [@restaurant, @review] do |f| %>

    <%= f.input :content %>
    <%= f.input :rating %>

    <%= f.submit class: "btn btn-primary" %>

  <% end %>
</div>